version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-delivery
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-server
      - payment-server
      - postpayment-server
      - status-server

  redis:
    image: redis:7
    container_name: redis-delivery
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # ==========================================
  # 어플리케이션 백엔드 서버 모듈들
  # ==========================================
  api-server:
    build:
      context: .
      args:
        MODULE_NAME: api-server
    container_name: api-server-delivery
    depends_on:
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-local} #local .env에는 해당 설정이 없으므로 local 적용
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  payment-server:
    build:
      context: .
      args:
        MODULE_NAME: Payment
    container_name: payment-delivery
    depends_on:
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-local}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PAYMENT_DB_HOST=${PAYMENT_DB_HOST}
      - PAYMENT_DB_PORT=${PAYMENT_DB_PORT:-3307}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  postpayment-server:
    build:
      context: .
      args:
        MODULE_NAME: PostPayment
    container_name: postpayment-delivery
    depends_on:
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-local}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  status-server:
    build:
      context: .
      args:
        MODULE_NAME: status-server
    container_name: status-delivery
    depends_on:
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-local}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-delivery
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-delivery
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
