events {
    worker_connections 1024; 
}

http {
    upstream api {
        server api-server:8080;
    }

    server {
        listen 80;

        location / {
            # 80 포트로 들어온 모든 통신을 정의해둔 백엔드 서버 그룹(api-server:8080)으로 토스함
            proxy_pass http://api;
            
            # 클라이언트가 최초로 접속할 때 입력했던 도메인 주소(Host)를 백엔드에 달아서 전달함
            proxy_set_header Host $host; 
            
            # Nginx를 거치며 IP가 가려지는 것을 막기 위해, 클라이언트의 진짜 원래 IP 주소를 알려줌
            proxy_set_header X-Real-IP $remote_addr;
            
            # 클라이언트가 여러 프록시를 징검다리처럼 거쳐온 경우, 그 IP들의 내역을 누적해서 기록해줌
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # 클라이언트가 최초에 http로 들어왔는지, https(보안 연결)로 들어왔는지 그 껍데기 정보를 알려줌
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
